import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

edata = pd.read_csv('Data/electronwcutsandperm.txt')
mdata = pd.read_csv('Data/muonwcutsandperm.txt')
plt.hist(edata['pT'],bins=int(np.floor(edata.size**(1/2))))
plt.axvline(x=edata['pT'].mean(),color='Red',ls='--')
plt.axvline(x=edata['pT'].median(),color='Black',ls='--')
print(edata['pT'].mean())
print(edata['pT'].median())
print(edata['pT'].min())
print(edata['pT'].max())
plt.title('Electron PT plot')
plt.xlabel('PT')
plt.ylabel('Frequency')
plt.xscale('log',base=10)
plt.savefig('Electron_pT_Plot.png')
plt.clf()
plt.hist(edata['phi'],bins=int(np.floor(edata.size**(1/2))))
plt.title('Electron Phi plot')
plt.xlabel('Phi')
plt.ylabel('Frequency')
plt.savefig('Electron_phi_Plot.png')
plt.clf()
plt.hist(edata['eta'],bins=int(np.floor(edata.size**(1/2))))
plt.title('Electron Eta plot')
plt.xlabel('Eta')
plt.ylabel('Frequency')
plt.savefig('Electron_eta_Plot.png')
plt.clf()
plt.hist(mdata['pT'],bins=int(np.floor(mdata.size**(1/2))))
plt.axvline(x=mdata['pT'].mean(),color='Red',ls='--')
plt.axvline(x=mdata['pT'].median(),color='Black',ls='--')
print(mdata['pT'].mean())
print(mdata['pT'].median())
print(mdata['pT'].min())
print(mdata['pT'].max())
plt.title('Muon PT plot')
plt.xlabel('PT')
plt.ylabel('Frequency')
plt.xscale('log',base=10)
plt.savefig('Muon_pT_Plot.png')
plt.clf()
plt.hist(mdata['phi'],bins=int(np.floor(mdata.size**(1/2))))
plt.title('Muon Phi plot')
plt.xlabel('Phi')
plt.ylabel('Frequency')
plt.savefig('Muon_phi_Plot.png')
plt.clf()
plt.hist(mdata['eta'],bins=int(np.floor(mdata.size**(1/2))))
plt.title('Muon Eta plot')
plt.xlabel('Eta')
plt.ylabel('Frequency')
plt.savefig('Muon_eta_Plot.png')
plt.clf()